'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace LoginService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="LoginServiceSoap", [Namespace]:="LoginService")>  _
    Partial Public Class LoginService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private LoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private msgHeaderValueField As MsgHeader
        
        Private LogoutOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.B1WebService.My.MySettings.Default.B1WebService_LoginService_LoginService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property MsgHeaderValue() As MsgHeader
            Get
                Return Me.msgHeaderValueField
            End Get
            Set
                Me.msgHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event LoginCompleted As LoginCompletedEventHandler
        
        '''<remarks/>
        Public Event LogoutCompleted As LogoutCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoginService/Login", RequestNamespace:="LoginService", ResponseNamespace:="http://www.sap.com/SBO/DIS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Login(ByVal DatabaseServer As String, ByVal DatabaseName As String, ByVal DatabaseType As LoginDatabaseType, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal DatabaseTypeSpecified As Boolean, ByVal CompanyUsername As String, ByVal CompanyPassword As String, ByVal Language As LoginLanguage, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal LanguageSpecified As Boolean, ByVal LicenseServer As String) As <System.Xml.Serialization.XmlElementAttribute("SessionID")> String
            Dim results() As Object = Me.Invoke("Login", New Object() {DatabaseServer, DatabaseName, DatabaseType, DatabaseTypeSpecified, CompanyUsername, CompanyPassword, Language, LanguageSpecified, LicenseServer})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LoginAsync(ByVal DatabaseServer As String, ByVal DatabaseName As String, ByVal DatabaseType As LoginDatabaseType, ByVal DatabaseTypeSpecified As Boolean, ByVal CompanyUsername As String, ByVal CompanyPassword As String, ByVal Language As LoginLanguage, ByVal LanguageSpecified As Boolean, ByVal LicenseServer As String)
            Me.LoginAsync(DatabaseServer, DatabaseName, DatabaseType, DatabaseTypeSpecified, CompanyUsername, CompanyPassword, Language, LanguageSpecified, LicenseServer, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LoginAsync(ByVal DatabaseServer As String, ByVal DatabaseName As String, ByVal DatabaseType As LoginDatabaseType, ByVal DatabaseTypeSpecified As Boolean, ByVal CompanyUsername As String, ByVal CompanyPassword As String, ByVal Language As LoginLanguage, ByVal LanguageSpecified As Boolean, ByVal LicenseServer As String, ByVal userState As Object)
            If (Me.LoginOperationCompleted Is Nothing) Then
                Me.LoginOperationCompleted = AddressOf Me.OnLoginOperationCompleted
            End If
            Me.InvokeAsync("Login", New Object() {DatabaseServer, DatabaseName, DatabaseType, DatabaseTypeSpecified, CompanyUsername, CompanyPassword, Language, LanguageSpecified, LicenseServer}, Me.LoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.LoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LoginCompleted(Me, New LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("MsgHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("LoginService/Logout", RequestNamespace:="LoginService", ResponseNamespace:="http://www.sap.com/SBO/DIS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Logout()
            Me.Invoke("Logout", New Object(-1) {})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LogoutAsync()
            Me.LogoutAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LogoutAsync(ByVal userState As Object)
            If (Me.LogoutOperationCompleted Is Nothing) Then
                Me.LogoutOperationCompleted = AddressOf Me.OnLogoutOperationCompleted
            End If
            Me.InvokeAsync("Logout", New Object(-1) {}, Me.LogoutOperationCompleted, userState)
        End Sub
        
        Private Sub OnLogoutOperationCompleted(ByVal arg As Object)
            If (Not (Me.LogoutCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LogoutCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sap.com/SBO/DIS"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.sap.com/SBO/DIS", IsNullable:=false)>  _
    Partial Public Class MsgHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private sessionIDField As String
        
        '''<remarks/>
        Public Property SessionID() As String
            Get
                Return Me.sessionIDField
            End Get
            Set
                Me.sessionIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="LoginService")>  _
    Public Enum LoginDatabaseType
        
        '''<remarks/>
        dst_MSSQL
        
        '''<remarks/>
        dst_DB_2
        
        '''<remarks/>
        dst_SYBASE
        
        '''<remarks/>
        dst_MSSQL2005
        
        '''<remarks/>
        dst_MAXDB
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="LoginService")>  _
    Public Enum LoginLanguage
        
        '''<remarks/>
        ln_Hebrew
        
        '''<remarks/>
        ln_Spanish_Ar
        
        '''<remarks/>
        ln_English
        
        '''<remarks/>
        ln_Polish
        
        '''<remarks/>
        ln_English_Sg
        
        '''<remarks/>
        ln_Spanish_Pa
        
        '''<remarks/>
        ln_English_Gb
        
        '''<remarks/>
        ln_German
        
        '''<remarks/>
        ln_Serbian
        
        '''<remarks/>
        ln_Danish
        
        '''<remarks/>
        ln_Norwegian
        
        '''<remarks/>
        ln_Italian
        
        '''<remarks/>
        ln_Hungarian
        
        '''<remarks/>
        ln_Chinese
        
        '''<remarks/>
        ln_Dutch
        
        '''<remarks/>
        ln_Finnish
        
        '''<remarks/>
        ln_Greek
        
        '''<remarks/>
        ln_Portuguese
        
        '''<remarks/>
        ln_Swedish
        
        '''<remarks/>
        ln_English_Cy
        
        '''<remarks/>
        ln_French
        
        '''<remarks/>
        ln_Spanish
        
        '''<remarks/>
        ln_Russian
        
        '''<remarks/>
        ln_Spanish_La
        
        '''<remarks/>
        ln_Czech_Cz
        
        '''<remarks/>
        ln_Slovak_Sk
        
        '''<remarks/>
        ln_Korean_Kr
        
        '''<remarks/>
        ln_Portuguese_Br
        
        '''<remarks/>
        ln_Japanese_Jp
        
        '''<remarks/>
        ln_Turkish_Tr
        
        '''<remarks/>
        ln_TrdtnlChinese_Hk
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub LoginCompletedEventHandler(ByVal sender As Object, ByVal e As LoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub LogoutCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
